### ISSUE TITLE
Fix all test classnames

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#101]
We should not have "root" in class names.

**Comment by pkgdemon** [comment]
Also as discussed we should verify classnames match between api, and webui tests as much as possible.  If possible I would like to look at making sure classnames show the order of tests run sequentially.  We have already done this for the individual tests.

**Comment by ericbsd** [comment]
In the API 1.0 tests, there are no more class one functions.

**Comment by rishabh27892** [comment]
just for the reference...
https://docs.google.com/document/d/1t9jlgBT1a0FWxngnmV1hma3hDsyGSlAI-5bdNEVZSDc/edit
