### ISSUE TITLE
VM cleanup can get stuck sometimes and require power off

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#113]
This job was stuck due to ixautomation --destroy-all-vm being stuck:

https://builds.ixsystems.com/jenkins/job/FreeNAS%20-%20FreeNAS%20Pipeline/job/PR-1081/2/console

I did vm list and then powered off the VM with vm poweroff.  Unfortunately that requires the name of the last running VM to cleanup.  I am not sure the best way to handle this yet just wanted to put it in a ticket so that I did not forget again.

**Comment by ericbsd** [comment]
We could revert to destroy the vm after the test is done like before.

**Comment by pkgdemon** [comment]
We can make this change from Jenkinsfile as well.  I would rather make change top stop VM after test from Jenkinsfile preserve the debug functionality when needed.  We can discuss further at the dev summit.  Not high priority at this point.  I just wanted to keep this ticket open to track the issue.

**Comment by pkgdemon** [comment]
This seems to do the trick for powering off all VMs.

```
ls /dev/vmm | xargs vmpoweroff
```

**Comment by pkgdemon** [comment]
https://github.com/freenas/freenas/commit/ffa6f3e352f6e5c02b64749f5c7422f4956846b0
https://github.com/freenas/webui/pull/669
