### ISSUE TITLE
If at least 1 ISO exists in some cases we use the wrong ISO automatically

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#12]
Not critical but just encountered when trying to test FreeBSD with FreeNAS present ISO in /ixautomation/vms/.iso it tried to use the FreeNAS ISO automatically.

**Comment by ericbsd** [comment]
Will probably do the same for TrueOS too.

**Comment by ericbsd** [comment]
eturgeon@eric-laptop /ixautomation> sudo ./jenkins.sh freenas-api-tests trueos
##########################################
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9016    0  9016    0     0   9016      0 --:--:--  0:00:01 --:--:--  4548
Already up-to-date.
Cloning with: git clone --depth=1 https://www.github.com/ixsystems/ixbuild.git /tmp/build/dVrF
Cloning into '/tmp/build/dVrF'...
warning: redirecting to https://github.com/ixsystems/ixbuild.git/
remote: Counting objects: 241, done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 241 (delta 76), reused 79 (delta 10), pack-reused 0
Receiving objects: 100% (241/241), 316.62 KiB | 964.00 KiB/s, done.
Resolving deltas: 100% (76/76), done.
vm_enable: YES -> YES
vm_dir: /ixautomation/vms -> /ixautomation/vms
/etc/rc.conf: net.link.bridge.ipfw=1: not found
cloned_interfaces: bridge0 tap0 -> bridge0 tap0
ifconfig_bridge0: addm ue0 addm tap0 up -> addm ue0 addm tap0 up
Please select which ISO to test (1-2):
    (1) /ixautomation/vms/.iso/FreeNAS-11-MASTER-201710260510-2bad025.iso
    (2) /ixautomation/vms/.iso/FreeNAS-11.0-U3.iso
Enter your selection and press [ENTER]:

**Comment by ericbsd** [comment]
It is why we add freenas/iso, trueos/iso, freebsd/iso.
