### ISSUE TITLE
When the first/last tap device is added or removed from bridge network drops

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#2]
This is due to a bug in FreeBSD which seems to be present in 11.1-RELEASE, and above.  

A similar bug report already exists for epair members:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221122

I need to implement a workaround for this for now, and file a bug report upstream to track the issue.  For the workaround we should make sure ixbuildbridge0 is created, and stored in /etc/rc.conf with at least one tap member.  As long as at least one tap device exists it will bypass the disconnection issue.

**Comment by amotin** [comment]
I've tried to reproduce this, and all I see is an uplink interface flap for several seconds due to bridge need to disable/restore of interface offload flags.  After NIC reinitialize the link, operation is restored.  Do I reproduce your issue, or you mean something different?

**Comment by pkgdemon** [comment]
@amotin I do see the re0 go down when watching /var/log/messages when adding, or removing a tap member.

Running the following causes no interruption:
root@joe-bsd:~ # ifconfig bridge create
bridge0
root@joe-bsd:~ # ifconfig bridge0 addm re0
root@joe-bsd:~ # ifconfig tap create
tap0

Running this:
root@joe-bsd:~ # ifconfig bridge0 addm tap0

Causes the following:
Oct 17 12:35:26 joe-bsd kernel: re0: link state changed to DOWN
Oct 17 12:35:26 joe-bsd kernel: bridge0: link state changed to DOWN
Oct 17 12:35:29 joe-bsd kernel: re0: link state changed to UP
Oct 17 12:35:29 joe-bsd kernel: bridge0: link state changed to UP
Oct 17 12:35:47 joe-bsd dhclient: New IP Address (re0): 10.231.1.107
Oct 17 12:35:47 joe-bsd dhclient: New Subnet Mask (re0): 255.255.0.0
Oct 17 12:35:47 joe-bsd dhclient: New Broadcast Address (re0): 10.231.255.255
Oct 17 12:35:47 joe-bsd dhclient: New Routers (re0): 10.231.0.1

**Comment by pkgdemon** [comment]
Added this workaround to get around the issue:

https://github.com/iXsystems/ixautomation/commit/823995151a2e926efd4bf6105f7d7d55a040ea7f

**Comment by pkgdemon** [comment]
@amotin I saw the updates in the FreeBSD ticket that this is due to interface capabilities.  That makes sense.  This is likely the same issue I am seeing, and does not sound like a bug after all.  Thanks.

**Comment by pkgdemon** [comment]
https://github.com/iXsystems/ixautomation/commit/85b98a450528dee653b271fbe513cad64bf1d341
