### ISSUE TITLE
Need better requirements/settings for testing against arbitrary systems.

### ISSUE THREAD

**Issue by darkfiberiru** [iXsystems/ixautomation#200]
*We don't list requirements like expected disks (tries to make a pool with ada0) or a way to configure this from cli. 

*Currently script fails because no vm name is set(which shouldn't be set when running against random host)

ixautomation doesn't seem to be in case that developer can run it against there machine they've been hot patching or testing code on.

Majority of testing is on vm but I don't see a reason why this shouldn't run on a vm created for it or a different system as appropriate.

**Comment by ericbsd** [comment]
API test has changed to get the disk on the disk instead of static drives.
