### ISSUE TITLE
Make vm_select_iso store all fetched isos in vms/iso

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#4]
This will prevent an unnecessary recopying of the ISO which causes a race condition when 6 jobs are executed in Jenkins.

/ixautomation/vms/.iso/FreeNAS-11-MASTER-201710230505-937d04e.i           0  B    0  Bps

**Comment by pkgdemon** [comment]
The end goal is to be able to remove the vm iso command by having the ISODIR variable also point to vms/iso so that vm install freenas freenas.iso knows to get the iso from vms/iso

**Comment by ericbsd** [comment]
This issue has been solved in the latest commit.
