### ISSUE TITLE
Rename expect scripts to install.exp, and boot.exp

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#55]

**Comment by pkgdemon** [comment]
https://github.com/iXsystems/ixautomation/commit/46d74150d62da56f29268fab723ecba8fda5520f
https://github.com/iXsystems/ixautomation/commit/8170cdb6cab5895a86b1bd991d864c900f7fd9a9

**Comment by ericbsd** [comment]
https://github.com/iXsystems/ixautomation/commit/6caae30fac21a02d86357af9ae32577f1c054457
