### ISSUE TITLE
Skip tests that require parameters when config.py is not present

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#71]
Currently runtest.py requires that config.py be present for function.sh.  We should make this optional and just skip tests that cannot be run if that file, and variables cannot be sourced.

**Comment by ericbsd** [comment]
I am testing https://github.com/ericbsd/freenas/commit/44db4b1da04b6cce87cbab92b945604c400b2e2e if everything is fin I will doe a pull request.

**Comment by ericbsd** [comment]
This is not related to the ixautomation framework it in the freenas/freenas/tests so if everything is fine we can release the new ixautomation.

**Comment by pkgdemon** [comment]
This is resolved in the framework.  We are just waiting on pull request from @ericbsd to fix as discussed in our meeting.
