### ISSUE TITLE
Add virtio-console suport to vm-bhyve

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#72]

**Comment by pkgdemon** [comment]
Filed a ticket with vm-bhyve project to see if this can be done upstream.  If not we can also consider forking, and try sending PR.

**Comment by pkgdemon** [comment]
https://lists.freebsd.org/pipermail/freebsd-virtualization/2016-July/004557.html

**Comment by araujobsd** [comment]
Hi did the changes, didn't replace nmdm just added virtio-console support: https://github.com/araujobsd/vm-bhyve/commit/47a03dc26f289fbd566fbefb026963067c50d890

**Comment by pkgdemon** [comment]
I forked anyway to get named nmdm pair support.
https://github.com/iXsystems/ixautomation/commit/e8ab512e0aa8aa2ae50c1566fddf54528f20d985
