### ISSUE TITLE
Webui test is not starting VM

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#74]
Part of the fix is here:

https://github.com/iXsystems/ixautomation/commit/eb8ce08022c93bcc84a491559c604124877e9153

I am not sure what is is required to create the VM before starting the tests like api-tests, and middlewared-tests.

**Comment by ericbsd** [comment]
https://github.com/iXsystems/ixautomation/commit/a40039d25929f9171d3bb63f9b57fc299cfea10a
