### ISSUE TITLE
FNASTESTIP shows invalid data for TrueOS

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#84]
Ideally we should get IP address info from guest tools instead.

**Comment by pkgdemon** [comment]
FNASTESTIP=See bugs.freebsd.org/bugzilla/show_bug.cgi?id=194485 for a patch.

**Comment by ericbsd** [comment]
I did fix the issue with https://github.com/iXsystems/ixautomation/commit/71a88df25eb6d3f6ad72b98750827b7fbd72717e
