### ISSUE TITLE
Allow jenkins.sh to run vm-tests and freenas-api-tests together

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#9]
We should allow for freenas-api-tests to run without creating a VM.  If a VM is desired we should be able to run ./jenkins.sh vm-tests freenas-api-tests to run both one after another.  

I think we could fix this by doing a case statement in vm-tests that looks at the output of $2.  If $2 is freenas-api-tests then run jenkins_api_tests.  Also SYSTYPE in jenkins.sh would need to change to $2 and then use cut to keep only the first portion freenas from $2 again.  We were doing this before but with $1.

**Comment by pkgdemon** [comment]
This should be a case statement in vm-tests I think that happens before vm_stop, and vm_destroy.  It should look at the output of $2 to determine if freenas-api-tests is $2.

**Comment by pkgdemon** [comment]
SYSTYPE=`echo $2 | cut -d '-' -f 1`

**Comment by ericbsd** [comment]
I did add that change https://github.com/iXsystems/ixautomation/commit/6b1e494b25260ed39690420a4f7c4599d529e70a which will work as ./jenkins.sh wm-tests freenas api-tests.
